int print_char(char);
char *concat_strings(char *s1, char *s2);
int str_len(char *str);
int strcmp(char *, char *);
int *print_prompt();
void print_env(char **);
char *find_path(char *, char **);
int ch_dir(char *cmd);
char *get_env_var(char *var, char **env);
void free_grid(char **grid, int n);
int grid_size(char **grid);
